// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg.proto

package proto

import (
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MsgType int32

const (
	MsgType_Common MsgType = 0
)

var MsgType_name = map[int32]string{
	0: "Common",
}

var MsgType_value = map[string]int32{
	"Common": 0,
}

func (x MsgType) String() string {
	return proto.EnumName(MsgType_name, int32(x))
}

func (MsgType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

type Data struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Desc                 map[string][]byte `protobuf:"bytes,2,rep,name=desc,proto3" json:"desc,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Data                 []byte            `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (m *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(m, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Data) GetDesc() map[string][]byte {
	if m != nil {
		return m.Desc
	}
	return nil
}

func (m *Data) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Msg struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 MsgType           `protobuf:"varint,2,opt,name=type,proto3,enum=proto.MsgType" json:"type,omitempty"`
	Desc                 map[string][]byte `protobuf:"bytes,3,rep,name=desc,proto3" json:"desc,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	DataList             []*Data           `protobuf:"bytes,4,rep,name=dataList,proto3" json:"dataList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Msg) Reset()         { *m = Msg{} }
func (m *Msg) String() string { return proto.CompactTextString(m) }
func (*Msg) ProtoMessage()    {}
func (*Msg) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{1}
}

func (m *Msg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Msg.Unmarshal(m, b)
}
func (m *Msg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Msg.Marshal(b, m, deterministic)
}
func (m *Msg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Msg.Merge(m, src)
}
func (m *Msg) XXX_Size() int {
	return xxx_messageInfo_Msg.Size(m)
}
func (m *Msg) XXX_DiscardUnknown() {
	xxx_messageInfo_Msg.DiscardUnknown(m)
}

var xxx_messageInfo_Msg proto.InternalMessageInfo

func (m *Msg) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Msg) GetType() MsgType {
	if m != nil {
		return m.Type
	}
	return MsgType_Common
}

func (m *Msg) GetDesc() map[string][]byte {
	if m != nil {
		return m.Desc
	}
	return nil
}

func (m *Msg) GetDataList() []*Data {
	if m != nil {
		return m.DataList
	}
	return nil
}

func init() {
	proto.RegisterEnum("proto.MsgType", MsgType_name, MsgType_value)
	proto.RegisterType((*Data)(nil), "proto.Data")
	proto.RegisterMapType((map[string][]byte)(nil), "proto.Data.DescEntry")
	proto.RegisterType((*Msg)(nil), "proto.Msg")
	proto.RegisterMapType((map[string][]byte)(nil), "proto.Msg.DescEntry")
}

func init() {
	proto.RegisterFile("msg.proto", fileDescriptor_c06e4cca6c2cc899)
}

var fileDescriptor_c06e4cca6c2cc899 = []byte{
	// 274 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x8f, 0xbd, 0x4e, 0xc3, 0x30,
	0x14, 0x85, 0xf1, 0x4f, 0x5b, 0x72, 0x8b, 0xaa, 0xc8, 0x6a, 0x55, 0xab, 0x2c, 0x51, 0x16, 0x02,
	0x43, 0x90, 0xca, 0x00, 0x62, 0x2c, 0x65, 0xa3, 0x8b, 0xc5, 0x0b, 0x98, 0xda, 0x8a, 0x22, 0x9a,
	0x26, 0x8a, 0x4d, 0xa5, 0xf0, 0x34, 0x3c, 0x11, 0x0f, 0xc4, 0x84, 0x62, 0x87, 0x80, 0x84, 0x58,
	0x98, 0x7c, 0xed, 0x73, 0x8e, 0xef, 0xf9, 0x20, 0x28, 0x4c, 0x96, 0x56, 0x75, 0x69, 0x4b, 0x36,
	0x70, 0xc7, 0x62, 0x7e, 0x90, 0xbb, 0x5c, 0x49, 0xab, 0x2f, 0xbf, 0x06, 0xaf, 0xc7, 0x6f, 0x08,
	0xe8, 0x5a, 0x5a, 0xc9, 0xe6, 0x80, 0x73, 0xc5, 0x51, 0x84, 0x92, 0x60, 0x35, 0xfa, 0x58, 0xd1,
	0x1a, 0x87, 0x44, 0xe0, 0x5c, 0xb1, 0x73, 0xa0, 0x4a, 0x9b, 0x2d, 0xc7, 0x11, 0x49, 0xc6, 0xcb,
	0x99, 0xcf, 0xa5, 0x6d, 0x26, 0x5d, 0x6b, 0xb3, 0xbd, 0xdf, 0xdb, 0xba, 0x11, 0xce, 0xc2, 0x4e,
	0x81, 0x2a, 0x69, 0x25, 0x27, 0x11, 0x4a, 0x4e, 0xdc, 0x2f, 0xaf, 0x38, 0x44, 0xc2, 0x3d, 0x2e,
	0xae, 0x21, 0xe8, 0xfd, 0x2c, 0x04, 0xf2, 0xac, 0x1b, 0xbf, 0x4e, 0xb4, 0x23, 0x9b, 0xc2, 0xe0,
	0x20, 0x77, 0x2f, 0x9a, 0xe3, 0x36, 0x2c, 0xfc, 0xe5, 0x16, 0xdf, 0xa0, 0xf8, 0x1d, 0x01, 0xd9,
	0x98, 0xec, 0xef, 0x86, 0x31, 0x50, 0xdb, 0x54, 0x3e, 0x39, 0x59, 0x4e, 0xba, 0x86, 0x1b, 0x93,
	0x3d, 0x36, 0x95, 0x16, 0x4e, 0x63, 0x49, 0x47, 0x41, 0x1c, 0xc5, 0xf4, 0xdb, 0xf3, 0x0b, 0xe2,
	0x0c, 0x8e, 0xdb, 0xbe, 0x0f, 0xb9, 0xb1, 0x9c, 0x3a, 0xf7, 0xf8, 0x07, 0xb3, 0xe8, 0xc5, 0x7f,
	0x03, 0x5d, 0xcc, 0x60, 0xd4, 0x95, 0x63, 0x00, 0xc3, 0xbb, 0xb2, 0x28, 0xca, 0x7d, 0x78, 0xf4,
	0x34, 0x74, 0x5b, 0xae, 0x3e, 0x03, 0x00, 0x00, 0xff, 0xff, 0x1b, 0x0a, 0x0b, 0xdc, 0xbe, 0x01,
	0x00, 0x00,
}
